/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Formulaire.java
 *
 * Created on 20 mars 2011, 11:52:49
 */

package formulaire;

/**
 *
 * @author yvan
 */
public class Formulaire extends javax.swing.JFrame {


    /** Creates new form Formulaire */
    public Formulaire() {
        initComponents();
        
        groupeGenre.add(radioButtonFemimin);
        groupeGenre.add(radioButtonMasculin);



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupeGenre = new javax.swing.ButtonGroup();
        boutonAnnuler = new javax.swing.JButton();
        boutonOK = new javax.swing.JButton();
        listCivilite = new javax.swing.JComboBox();
        labelNom = new javax.swing.JLabel();
        textFieldNom = new javax.swing.JTextField();
        labelPrenom = new javax.swing.JLabel();
        textFieldPrenom = new javax.swing.JTextField();
        labelNomDeJeuneFille = new javax.swing.JLabel();
        textFieldNomDeJeuneFille = new javax.swing.JTextField();
        radioButtonMasculin = new javax.swing.JRadioButton();
        radioButtonFemimin = new javax.swing.JRadioButton();
        labelAge = new javax.swing.JLabel();
        textFieldAge = new javax.swing.JTextField();
        labelDateDeNaissance = new javax.swing.JLabel();
        textFieldJourDeNaissance = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textFieldMoisDeNaissance = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldAnneeDeNaissance = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boutonAnnuler.setText("Annuler");

        boutonOK.setText("Ok");
        boutonOK.setEnabled(false);

        listCivilite.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Mme", "Mlle", "M." }));

        labelNom.setText("Nom");

        textFieldNom.setColumns(20);

        labelPrenom.setText("Prénom");

        textFieldPrenom.setColumns(20);

        labelNomDeJeuneFille.setText("Nom de jeune fille");

        textFieldNomDeJeuneFille.setColumns(20);

        radioButtonMasculin.setText("Masculin");

        radioButtonFemimin.setText("Feminin");

        labelAge.setText("Age");

        textFieldAge.setColumns(3);

        labelDateDeNaissance.setText("Date de naissance");

        textFieldJourDeNaissance.setColumns(2);
        textFieldJourDeNaissance.setToolTipText("jj");
        textFieldJourDeNaissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldJourDeNaissanceActionPerformed(evt);
            }
        });

        jLabel1.setText("/");

        textFieldMoisDeNaissance.setColumns(2);
        textFieldMoisDeNaissance.setToolTipText("mm");
        textFieldMoisDeNaissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldMoisDeNaissanceActionPerformed(evt);
            }
        });

        jLabel2.setText("/");

        textFieldAnneeDeNaissance.setColumns(4);
        textFieldAnneeDeNaissance.setToolTipText("aaaa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listCivilite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPrenom)
                                    .addComponent(textFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNom)
                                    .addComponent(textFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNomDeJeuneFille)
                                    .addComponent(textFieldNomDeJeuneFille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioButtonMasculin)
                                    .addComponent(radioButtonFemimin)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAge)
                                    .addComponent(textFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDateDeNaissance)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textFieldJourDeNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel1)
                                        .addGap(4, 4, 4)
                                        .addComponent(textFieldMoisDeNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabel2)
                                        .addGap(4, 4, 4)
                                        .addComponent(textFieldAnneeDeNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(boutonOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boutonAnnuler)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listCivilite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonMasculin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrenom)
                    .addComponent(radioButtonFemimin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNomDeJeuneFille)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNomDeJeuneFille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAge)
                    .addComponent(labelDateDeNaissance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldJourDeNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldMoisDeNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldAnneeDeNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonAnnuler)
                    .addComponent(boutonOK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldJourDeNaissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldJourDeNaissanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldJourDeNaissanceActionPerformed

    private void textFieldMoisDeNaissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldMoisDeNaissanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldMoisDeNaissanceActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAnnuler;
    private javax.swing.JButton boutonOK;
    private javax.swing.ButtonGroup groupeGenre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelAge;
    private javax.swing.JLabel labelDateDeNaissance;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelNomDeJeuneFille;
    private javax.swing.JLabel labelPrenom;
    private javax.swing.JComboBox listCivilite;
    private javax.swing.JRadioButton radioButtonFemimin;
    private javax.swing.JRadioButton radioButtonMasculin;
    private javax.swing.JTextField textFieldAge;
    private javax.swing.JTextField textFieldAnneeDeNaissance;
    private javax.swing.JTextField textFieldJourDeNaissance;
    private javax.swing.JTextField textFieldMoisDeNaissance;
    private javax.swing.JTextField textFieldNom;
    private javax.swing.JTextField textFieldNomDeJeuneFille;
    private javax.swing.JTextField textFieldPrenom;
    // End of variables declaration//GEN-END:variables

}
