package formulaire;

import commande.Command;
import commande.SetTextCommand;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JTextField;

/**
 *
 * @author yvan
 */
public class Formulaire extends javax.swing.JFrame implements ActionListener, FocusListener {

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupeGenre = new javax.swing.ButtonGroup();
        boutonAnnuler = new javax.swing.JButton();
        boutonOK = new javax.swing.JButton();
        listCivilite = new javax.swing.JComboBox();
        labelNom = new javax.swing.JLabel();
        textFieldNom = new javax.swing.JTextField();
        labelPrenom = new javax.swing.JLabel();
        textFieldPrenom = new javax.swing.JTextField();
        labelNomDeJeuneFille = new javax.swing.JLabel();
        textFieldNomDeJeuneFille = new javax.swing.JTextField();
        radioButtonMasculin = new javax.swing.JRadioButton();
        radioButtonFemimin = new javax.swing.JRadioButton();
        labelAge = new javax.swing.JLabel();
        textFieldAge = new javax.swing.JTextField();
        labelDateDeNaissance = new javax.swing.JLabel();
        textFieldJourDeNaissance = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textFieldMoisDeNaissance = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldAnneeDeNaissance = new javax.swing.JTextField();
        boutonToutRefaire = new javax.swing.JButton();
        boutonRefaire = new javax.swing.JButton();
        boutonToutDefaire = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boutonAnnuler.setText("Annuler");

        boutonOK.setText("Ok");
        boutonOK.setEnabled(false);

        listCivilite.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Mme", "Mlle", "M." }));

        labelNom.setText("Nom");

        textFieldNom.setColumns(20);

        labelPrenom.setText("Prénom");

        textFieldPrenom.setColumns(20);

        labelNomDeJeuneFille.setText("Nom de jeune fille");

        textFieldNomDeJeuneFille.setColumns(20);

        radioButtonMasculin.setText("Masculin");

        radioButtonFemimin.setText("Feminin");

        labelAge.setText("Age");

        textFieldAge.setColumns(3);

        labelDateDeNaissance.setText("Date de naissance");

        textFieldJourDeNaissance.setColumns(2);
        textFieldJourDeNaissance.setToolTipText("jj");
        textFieldJourDeNaissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldJourDeNaissanceActionPerformed(evt);
            }
        });

        jLabel1.setText("/");

        textFieldMoisDeNaissance.setColumns(2);
        textFieldMoisDeNaissance.setToolTipText("mm");
        textFieldMoisDeNaissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldMoisDeNaissanceActionPerformed(evt);
            }
        });

        jLabel2.setText("/");

        textFieldAnneeDeNaissance.setColumns(4);
        textFieldAnneeDeNaissance.setToolTipText("aaaa");

        boutonToutRefaire.setText(">|");
        boutonToutRefaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonToutRefaireActionPerformed(evt);
            }
        });

        boutonRefaire.setText(">");

        boutonToutDefaire.setText("|<");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listCivilite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPrenom)
                                    .addComponent(textFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNom)
                                    .addComponent(textFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNomDeJeuneFille)
                                    .addComponent(textFieldNomDeJeuneFille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioButtonMasculin)
                                    .addComponent(radioButtonFemimin)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAge)
                                    .addComponent(textFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDateDeNaissance)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textFieldJourDeNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel1)
                                        .addGap(4, 4, 4)
                                        .addComponent(textFieldMoisDeNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabel2)
                                        .addGap(4, 4, 4)
                                        .addComponent(textFieldAnneeDeNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boutonToutDefaire)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonRefaire)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boutonToutRefaire)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boutonOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boutonAnnuler)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listCivilite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonMasculin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrenom)
                    .addComponent(radioButtonFemimin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNomDeJeuneFille)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNomDeJeuneFille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAge)
                    .addComponent(labelDateDeNaissance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldJourDeNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldMoisDeNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldAnneeDeNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonAnnuler)
                    .addComponent(boutonOK)
                    .addComponent(boutonToutRefaire)
                    .addComponent(boutonRefaire)
                    .addComponent(boutonToutDefaire))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldJourDeNaissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldJourDeNaissanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldJourDeNaissanceActionPerformed

    private void textFieldMoisDeNaissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldMoisDeNaissanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldMoisDeNaissanceActionPerformed

    private void boutonToutRefaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonToutRefaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonToutRefaireActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Formulaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAnnuler;
    private javax.swing.JButton boutonOK;
    private javax.swing.JButton boutonRefaire;
    private javax.swing.JButton boutonToutDefaire;
    private javax.swing.JButton boutonToutRefaire;
    private javax.swing.ButtonGroup groupeGenre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelAge;
    private javax.swing.JLabel labelDateDeNaissance;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelNomDeJeuneFille;
    private javax.swing.JLabel labelPrenom;
    private javax.swing.JComboBox listCivilite;
    private javax.swing.JRadioButton radioButtonFemimin;
    private javax.swing.JRadioButton radioButtonMasculin;
    private javax.swing.JTextField textFieldAge;
    private javax.swing.JTextField textFieldAnneeDeNaissance;
    private javax.swing.JTextField textFieldJourDeNaissance;
    private javax.swing.JTextField textFieldMoisDeNaissance;
    private javax.swing.JTextField textFieldNom;
    private javax.swing.JTextField textFieldNomDeJeuneFille;
    private javax.swing.JTextField textFieldPrenom;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Command> commandes = new ArrayList<>();
    private Iterator<Command> commandIterator = null;

    /**
     * Creates new form Formulaire
     */
    public Formulaire() {
        initComponents();

        groupeGenre.add(radioButtonFemimin);
        groupeGenre.add(radioButtonMasculin);

        boutonRefaire.setEnabled(false);
        boutonToutRefaire.setEnabled(false);

        radioButtonMasculin.addActionListener(this);
        radioButtonFemimin.addActionListener(this);
        boutonAnnuler.addActionListener(this);
        textFieldAge.addActionListener(this);
        textFieldAnneeDeNaissance.addActionListener(this);
        textFieldMoisDeNaissance.addActionListener(this);
        textFieldJourDeNaissance.addActionListener(this);
        textFieldNom.addActionListener(this);
        textFieldNomDeJeuneFille.addActionListener(this);
        textFieldPrenom.addActionListener(this);
        textFieldAge.addFocusListener(this);
        textFieldAnneeDeNaissance.addFocusListener(this);
        textFieldMoisDeNaissance.addFocusListener(this);
        textFieldJourDeNaissance.addFocusListener(this);
        textFieldNom.addFocusListener(this);
        textFieldNomDeJeuneFille.addFocusListener(this);
        textFieldPrenom.addFocusListener(this);
        listCivilite.addActionListener(this);
        boutonToutRefaire.addActionListener(this);
        boutonRefaire.addActionListener(this);
        boutonToutDefaire.addActionListener(this);

    }

    private void radioButtonMasculinActionPerformed() {
        textFieldNomDeJeuneFille.setText("");
        textFieldNomDeJeuneFille.setVisible(false);
        labelNomDeJeuneFille.setVisible(false);
        listCivilite.removeActionListener(Formulaire.this);
        listCivilite.setSelectedIndex(3);
        listCivilite.addActionListener(Formulaire.this);
        commandes.add(new Command() {
            @Override
            public void execute() {
                radioButtonMasculin.setSelected(true);
            }
        });
    }

    private void radioButtonFemininActionPerformed() {
        textFieldNomDeJeuneFille.setVisible(true);
        labelNomDeJeuneFille.setVisible(true);
        listCivilite.removeActionListener(Formulaire.this);
        listCivilite.setSelectedIndex(0);
        listCivilite.addActionListener(Formulaire.this);
        commandes.add(new Command() {
            @Override
            public void execute() {
                radioButtonMasculinActionPerformed();
            }
        });
    }

    private void boutonAnnulerActionPerformed() {
        textFieldNomDeJeuneFille.setVisible(true);
        labelNomDeJeuneFille.setVisible(true);
        listCivilite.removeActionListener(Formulaire.this);
        listCivilite.setSelectedIndex(0);
        listCivilite.addActionListener(Formulaire.this);
        boutonOK.setEnabled(false);
        textFieldAge.setText("");
        textFieldAnneeDeNaissance.setText("");
        textFieldJourDeNaissance.setText("");
        textFieldMoisDeNaissance.setText("");
        textFieldNom.setText("");
        textFieldNomDeJeuneFille.setText("");
        textFieldPrenom.setText("");
        groupeGenre.clearSelection();
        commandIterator = commandes.iterator();
        boutonToutRefaire.setEnabled(true);
        boutonRefaire.setEnabled(true);
    }

    private void boutonToutRefaireActionPerformed() {
        Iterator<Command> i = commandes.iterator();
        while (i.hasNext()) {
            i.next().execute();
        }
        boutonRefaire.setEnabled(false);
        boutonToutRefaire.setEnabled(false);
    }

    private void boutonRefaireActionPerformed() {
        if (commandIterator.hasNext()) {
            commandIterator.next().execute();
        } else {
            boutonRefaire.setEnabled(false);
            boutonToutRefaire.setEnabled(false);
        }
    }

    private void listCiviliteActionPerformed() {
        switch (listCivilite.getSelectedIndex()) {
            case 1:
                textFieldNomDeJeuneFille.setVisible(false);
                labelNomDeJeuneFille.setVisible(false);
                textFieldNomDeJeuneFille.setText("");
                radioButtonFemimin.setSelected(true);
                break;
            case 2:
                textFieldNomDeJeuneFille.setVisible(true);
                labelNomDeJeuneFille.setVisible(true);
                textFieldNomDeJeuneFille.setText("");
                radioButtonFemimin.setSelected(true);
                break;
            case 3:
                textFieldNomDeJeuneFille.setVisible(false);
                labelNomDeJeuneFille.setVisible(false);
                textFieldNomDeJeuneFille.setText("");
                radioButtonMasculin.setSelected(true);
                break;
        }
        commandes.add(new SelectCivility(listCivilite.getSelectedIndex()));
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == radioButtonMasculin) {
            radioButtonMasculinActionPerformed();
        } else if (e.getSource() == radioButtonFemimin) {
            radioButtonFemininActionPerformed();
        } else if (e.getSource() == boutonAnnuler) {
            boutonAnnulerActionPerformed();
        } else if (e.getSource() instanceof JTextField) {
            JTextField jtf = (JTextField) e.getSource();
            commandes.add(new SetTextCommand(jtf, jtf.getText()));
        } else if (e.getSource() == listCivilite) {
            listCiviliteActionPerformed();
        } else if (e.getSource() == boutonToutDefaire) {
            boutonAnnulerActionPerformed();
        } else if (e.getSource() == boutonToutRefaire) {
            boutonToutRefaireActionPerformed();
        } else if (e.getSource() == boutonRefaire) {
            boutonRefaireActionPerformed();
        }
    }

    @Override
    public void focusGained(FocusEvent e) {
    }

    @Override
    public void focusLost(FocusEvent e) {
        if (e.getSource() instanceof JTextField) {
            JTextField jtf = (JTextField) e.getSource();
            commandes.add(new SetTextCommand(jtf, jtf.getText()));
        }
    }

    public class SelectCivility implements Command {

        private final int pos;

        public SelectCivility(int pos) {
            this.pos = pos;
        }

        @Override
        public void execute() {

            listCivilite.removeActionListener(Formulaire.this);
            listCivilite.setSelectedIndex(pos);
            switch (pos) {
                case 2:
                    textFieldNomDeJeuneFille.setVisible(false);
                    labelNomDeJeuneFille.setVisible(false);
                    textFieldNomDeJeuneFille.setText("");
                    radioButtonFemimin.setSelected(true);
                    break;
                case 1:
                    textFieldNomDeJeuneFille.setVisible(true);
                    labelNomDeJeuneFille.setVisible(true);
                    textFieldNomDeJeuneFille.setText("");
                    radioButtonFemimin.setSelected(true);
                    break;
                case 3:
                    textFieldNomDeJeuneFille.setVisible(false);
                    labelNomDeJeuneFille.setVisible(false);
                    textFieldNomDeJeuneFille.setText("");
                    radioButtonMasculin.setSelected(true);
                    break;
            }
            listCivilite.addActionListener(Formulaire.this);
        }

    }

}
